<a href="https://colab.research.google.com/github/leasju/pi_educacao_qualidade/blob/main/ORIGINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assstente IA -Chatbot https://github.com/streamlit/demo-ai-assistant

Dashboard Estoque https://github.com/64squaresapexllp/snowflake_health

Chatbot https://github.com/streamlit/llm-examples

Analise de algo https://github.com/tylerjrichards/streamlit_goodreads_app

# **Banco de Dados - Não Relacional**

**Instituição:** Pontifícia Universidade Católica de Campinas

**Curso:** Ciência de Dados e Inteligência Artificial

**Professor:** Felipe Cavalaro  

---

## Integrantes

| Nome | RA |
| :--- | :--- |
| Alice Pasolini | 25012938 |
| Enzo Guerra | 25007153 |
| Guilherme Cintra | 25004996 |
| Julia Leandro | 25009148 |
| Lavínia Oliveira | 25894981 |

### **ODS 4 - Educação e Qualidade**

### Indicadores Escolhidos

| Indicador | Fonte do Dataset |
| :--- | :--- |
| Proficiência do SARESP por município | [Acessar dados](https://dados.educacao.sp.gov.br/dataset/profici%C3%AAncia-do-sistema-de-avalia%C3%A7%C3%A3o-de-rendimento-escolar-do-estado-de-s%C3%A3o-paulo-saresp-4) |
| Fluxo escolar por município | [Acessar dados](https://dados.educacao.sp.gov.br/dataset/fluxo-escolar-por-munic%C3%ADpio) |
| Ausências por servidor (Faltas e absenteísmo) | [Acessar dados](https://dados.educacao.sp.gov.br/dataset/aus%C3%AAncias-por-servidor) |
| Censo Escolar (Faltas e absenteísmo) | [Acessar dados](https://dados.educacao.sp.gov.br/dataset/aus%C3%AAncias-por-servidor) |

---
## **🖥️ | IMPLEMENTAÇÃO: ELT** (Extract, Load, Transform)

### **Estrutura Base**
- Bibliotecas e pacotes
- Funções
- Variáveis globais

In [1]:
!git clone https://github.com/tylerjrichards/streamlit_goodreads_app -q
%cd streamlit_goodreads_app
!pip install streamlit -q

/content/streamlit_goodreads_app
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 44.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 77.3 MB/s eta 0:00:00

pymongo

In [2]:
!pip install pandas pymongo -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 18.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 9.7 MB/s eta 0:00:00

In [3]:
# DataFrames e funções auxiliares
import pandas as pd
import numpy as np
import time

# Gráficos
import matplotlib.pyplot as plt
import seaborn as sns

# Grafos
import networkx as nx

# Conexão com o MongoDB
from pymongo import MongoClient

# Formatar encoding dos arquivos
from urllib.parse import quote
import unicodedata

### Streamlit Dashboard

In [4]:

'''%%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np

st.title('Uber pickups in NYC')

DATE_COLUMN = 'date/time'
DATA_URL = ('https://s3-us-west-2.amazonaws.com/'
            'streamlit-demo-data/uber-raw-data-sep14.csv.gz')

@st.cache_data
def load_data(nrows):
    data = pd.read_csv(DATA_URL, nrows=nrows)
    lowercase = lambda x: str(x).lower()
    data.rename(lowercase, axis='columns', inplace=True)
    data[DATE_COLUMN] = pd.to_datetime(data[DATE_COLUMN])
    return data

data_load_state = st.text('Loading data...')
data = load_data(10000)
data_load_state.text("Done! (using st.cache_data)")

if st.checkbox('Show raw data'):
    st.subheader('Raw data')
    st.write(data)

st.subheader('Number of pickups by hour')
hist_values = np.histogram(data[DATE_COLUMN].dt.hour, bins=24, range=(0,24))[0]
st.bar_chart(hist_values)

# Some number in the range 0-23
hour_to_filter = st.slider('hour', 0, 23, 17)
filtered_data = data[data[DATE_COLUMN].dt.hour == hour_to_filter]

st.subheader('Map of all pickups at %s:00' % hour_to_filter)
st.map(filtered_data)'''

'%%writefile app.py\nimport streamlit as st\nimport pandas as pd\nimport numpy as np\n\nst.title(\'Uber pickups in NYC\')\n\nDATE_COLUMN = \'date/time\'\nDATA_URL = (\'https://s3-us-west-2.amazonaws.com/\'\n            \'streamlit-demo-data/uber-raw-data-sep14.csv.gz\')\n\n@st.cache_data\ndef load_data(nrows):\n    data = pd.read_csv(DATA_URL, nrows=nrows)\n    lowercase = lambda x: str(x).lower()\n    data.rename(lowercase, axis=\'columns\', inplace=True)\n    data[DATE_COLUMN] = pd.to_datetime(data[DATE_COLUMN])\n    return data\n\ndata_load_state = st.text(\'Loading data...\')\ndata = load_data(10000)\ndata_load_state.text("Done! (using st.cache_data)")\n\nif st.checkbox(\'Show raw data\'):\n    st.subheader(\'Raw data\')\n    st.write(data)\n\nst.subheader(\'Number of pickups by hour\')\nhist_values = np.histogram(data[DATE_COLUMN].dt.hour, bins=24, range=(0,24))[0]\nst.bar_chart(hist_values)\n\n# Some number in the range 0-23\nhour_to_filter = st.slider(\'hour\', 0, 23, 17)\nfiltered_data = data[data[DATE_COLUMN].dt.hour == hour_to_filter]\n\nst.subheader(\'Map of all pickups at %s:00\' % hour_to_filter)\nst.map(filtered_data)'

In [5]:
with open("requirements.txt", "r") as f:
    content = f.read()

content = content.replace("numpy==1.23.5", "numpy>=1.26")

with open("requirements.txt", "w") as f:
    f.write(content)

In [6]:
'''!pip install -r requirements.txt -q
!npm install localtunnel -q'''

'!pip install -r requirements.txt -q\n!npm install localtunnel -q'

In [7]:
!curl ipv4.icanhazip.com

34.138.96.18

In [8]:
'''!streamlit run app.py &>/dev/null&
!npx localtunnel --port 8501'''

'!streamlit run app.py &>/dev/null&\n!npx localtunnel --port 8501'

### Funções e estruturas genéricas para a leitura dos Datasets

URL Base - GitHub

In [9]:
URLsaresp = "https://raw.githubusercontent.com/leasju/pi_educacao_qualidade/main/Proficiencia%20do%20SARESP"
URLfluxo = "https://raw.githubusercontent.com/leasju/pi_educacao_qualidade/main/Fluxo%20Escolar"
URLausencia = "https://raw.githubusercontent.com/leasju/pi_educacao_qualidade/main/Ausencia"
URLcenso = "https://raw.githubusercontent.com/leasju/pi_educacao_qualidade/main/Censo%20Escolar"

Configuração dos anos nos Datasets

In [10]:
# Dicionário com os anos
dict_ano = {
    22: 2022,
    23: 2023,
    24: 2024
}

In [11]:
# Adiciona a coluna 'Ano' aos datasets
def add_col(df, ano):
    df["Ano"] = ano
    return df

Função que realiza a leitura dos Datasets e os concatena ao final

In [12]:
def le_dataset(base_url, links):
    lista_dfs = []

    for k, v in links.items():

        # Detecta formato do dicionário
        # ano : {"nome_arquivo"}
        if isinstance(k, int):
            ano = k
            nome = v
        # "nome_arquivo" : ano
        else:
            nome = k
            ano = v

        nome_encoded = quote(nome)
        url = f"{base_url}/{nome_encoded}"

        df = None

        for enc in ['utf-8-sig', 'latin-1']:
            try:
                # print(f"Tentando: {url}")
                df = pd.read_csv(url, sep=';', encoding=enc)
                # print(f"OK: {nome}")
                break
            except Exception as e:
                # print(f"ERRO: {nome} | {e}")
                continue

        if df is not None:
            for chave in dict_ano:
                if str(chave) in nome:
                    df = add_col(df, dict_ano[chave])
                    break
            df.columns = df.columns.str.upper()
            lista_dfs.append(df)
        time.sleep(2)

    return pd.concat(lista_dfs, ignore_index=True)

Lista da região metropolitana de Campinas (10 principais municípios)

In [13]:
regiaoCampinas = ['CAMPINAS','HORTOLANDIA','SUMARE','INDAIATUBA','PAULINIA','AMERICANA','VALINHOS','VINHEDO','ITATIBA','SANTA BARBARA D\'OESTE']

### ⚪ **DATASET SARESP**

Leitura e análise do dataframe

In [14]:
sarespLinks = {
    2022: "Proficiencia do SARESP por municipio de 2022_0.csv",
    2023: "Proficiencia do SARESP por Municipio de 2023_0.csv",
    2024: "Proficiencia do SARESP por Municipio de 2024_0.csv"
}

sarespDF = le_dataset(URLsaresp, sarespLinks)
sarespDF

,DEPADM,DEPBOL,NOMEDEPBOL,CODRMET,CODMUN,MUN,SERIE_ANO,COD_PER,PERIODO,CO_COMP,DS_COMP,MEDPROF,ANO
0,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,1,MANHÃ,1,LÍNGUA PORTUGUESA,"173,4",2023
1,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,1,MANHÃ,2,MATEMÁTICA,"165,3",2023
2,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,2,TARDE,1,LÍNGUA PORTUGUESA,"168,2",2023
3,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,2,TARDE,2,MATEMÁTICA,"160,4",2023
4,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,9,GERAL,1,LÍNGUA PORTUGUESA,"170,1",2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21491,2,2,Rede Municipal,5,794,TRABIJU,5º Ano EF,9,GERAL,2,MATEMÁTICA,"230,1",2024
21492,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,1,MANHÃ,1,LÍNGUA PORTUGUESA,"235,8",2024
21493,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,1,MANHÃ,2,MATEMÁTICA,"265,4",2024
21494,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,9,GERAL,1,LÍNGUA PORTUGUESA,"235,8",2024
21495,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,9,GERAL,2,MATEMÁTICA,"265,4",2024

In [15]:
# Cópia do dataframe original (Caso precise)
sarespDFOriginal = sarespDF.copy()
sarespDFOriginal

,DEPADM,DEPBOL,NOMEDEPBOL,CODRMET,CODMUN,MUN,SERIE_ANO,COD_PER,PERIODO,CO_COMP,DS_COMP,MEDPROF,ANO
0,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,1,MANHÃ,1,LÍNGUA PORTUGUESA,"173,4",2023
1,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,1,MANHÃ,2,MATEMÁTICA,"165,3",2023
2,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,2,TARDE,1,LÍNGUA PORTUGUESA,"168,2",2023
3,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,2,TARDE,2,MATEMÁTICA,"160,4",2023
4,1,1,Rede Estadual,1,100,SAO PAULO,2º Ano EF,9,GERAL,1,LÍNGUA PORTUGUESA,"170,1",2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21491,2,2,Rede Municipal,5,794,TRABIJU,5º Ano EF,9,GERAL,2,MATEMÁTICA,"230,1",2024
21492,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,1,MANHÃ,1,LÍNGUA PORTUGUESA,"235,8",2024
21493,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,1,MANHÃ,2,MATEMÁTICA,"265,4",2024
21494,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,9,GERAL,1,LÍNGUA PORTUGUESA,"235,8",2024
21495,2,2,Rede Municipal,5,794,TRABIJU,9º Ano EF,9,GERAL,2,MATEMÁTICA,"265,4",2024

Normalização do dataframe

In [16]:
apagarCol = ['DEPADM','DEPBOL','CODRMET','CODMUN','COD_PER','CO_COMP']
sarespDF = sarespDFOriginal.drop(columns=apagarCol)
sarespDF.head().style.hide(axis="index")

sarespDF = sarespDF.replace(',', '.', regex=True)
sarespDF['MEDPROF'] = sarespDF['MEDPROF'].astype('float')


sarespDF = sarespDF[sarespDF.MUN.isin(regiaoCampinas)]

sarespDF = sarespDF.reset_index(drop=True)
sarespDF = sarespDF.rename(columns={
    'MUN': 'MUNICÍPIOS',
    'DS_COMP': 'COMPETÊNCIA',
    'MEDPROF': 'MÉDIA_PROFICIÊNCIA',
    'NOMEDEPBOL': 'REDE',
})
sarespDF

,REDE,MUNICÍPIOS,SERIE_ANO,PERIODO,COMPETÊNCIA,MÉDIA_PROFICIÊNCIA,ANO
0,Rede Estadual,AMERICANA,2º Ano EF,MANHÃ,LÍNGUA PORTUGUESA,175.8,2023
1,Rede Estadual,AMERICANA,2º Ano EF,MANHÃ,MATEMÁTICA,165.8,2023
2,Rede Estadual,AMERICANA,2º Ano EF,TARDE,LÍNGUA PORTUGUESA,175.8,2023
3,Rede Estadual,AMERICANA,2º Ano EF,TARDE,MATEMÁTICA,163.0,2023
4,Rede Estadual,AMERICANA,2º Ano EF,GERAL,LÍNGUA PORTUGUESA,175.8,2023
...,...,...,...,...,...,...,...
459,Rede Municipal,HORTOLANDIA,5º Ano EF,MANHÃ,MATEMÁTICA,220.4,2024
460,Rede Municipal,HORTOLANDIA,5º Ano EF,TARDE,LÍNGUA PORTUGUESA,210.0,2024
461,Rede Municipal,HORTOLANDIA,5º Ano EF,TARDE,MATEMÁTICA,219.7,2024
462,Rede Municipal,HORTOLANDIA,5º Ano EF,GERAL,LÍNGUA PORTUGUESA,210.7,2024
463,Rede Municipal,HORTOLANDIA,5º Ano EF,GERAL,MATEMÁTICA,220.1,2024

Download

In [17]:
sarespDF.to_csv('sarespDF.csv', index=False)

#### (PARTE DO ENZO) Gráficos

In [18]:

'''# Cálculo dos limites para tratar os outliers
Q1 = sarespDF['MÉDIA_PROFICIÊNCIA'].quantile(0.25)

Q3 = sarespDF['MÉDIA_PROFICIÊNCIA'].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# -----------------------------------

print(sarespDF['MÉDIA_PROFICIÊNCIA'].describe())
plt.figure(figsize=(10, 6))
sns.boxplot(data=sarespDF, x=sarespDF.MUNICÍPIOS, y=sarespDF.MÉDIA_PROFICIÊNCIA, hue=sarespDF["MUNICÍPIOS"])
plt.title("Média de proficiência por município")
plt.xticks(fontsize=8, rotation=30)
plt.xlabel("Municípios")
plt.ylabel("Média de Proficiência")
plt.ylim(limite_inferior,limite_superior)
plt.show()
'''

'# Cálculo dos limites para tratar os outliers\nQ1 = sarespDF[\'MÉDIA_PROFICIÊNCIA\'].quantile(0.25)\n\nQ3 = sarespDF[\'MÉDIA_PROFICIÊNCIA\'].quantile(0.75)\nIQR = Q3 - Q1\n\nlimite_inferior = Q1 - 1.5 * IQR\nlimite_superior = Q3 + 1.5 * IQR\n\n# -----------------------------------\n\nprint(sarespDF[\'MÉDIA_PROFICIÊNCIA\'].describe())\nplt.figure(figsize=(10, 6))\nsns.boxplot(data=sarespDF, x=sarespDF.MUNICÍPIOS, y=sarespDF.MÉDIA_PROFICIÊNCIA, hue=sarespDF["MUNICÍPIOS"])\nplt.title("Média de proficiência por município")\nplt.xticks(fontsize=8, rotation=30)\nplt.xlabel("Municípios")\nplt.ylabel("Média de Proficiência")\nplt.ylim(limite_inferior,limite_superior)\nplt.show()\n'

### ⚪ **DATASET FLUXO ESCOLAR DOS ALUNOS**
Aprovação e Reprovação

Leitura dos datasets

In [19]:
fluxoLinks = {
    2022: "Fluxo Escolar 2022 - por municipio.csv",
    2023: "Fluxo Escolar 2023 - por município.csv",
    2024: "Fluxo Escolar 2024 - por municipio.csv"
}

fluxoDF = le_dataset(URLfluxo, fluxoLinks)
fluxoDF

,ANO_LETIVO,NM_DIRETORIA,NM_MUNICIPIO,CD_REDE_ENSINO,APR_1,REP_1,ABA_1,APR_2,REP_2,ABA_2,APR_3,REP_3,ABA_3,ANO
0,2022,ADAMANTINA,ADAMANTINA,1,0,0,0,"99,61","0,29","0,1","98,97","0,83","0,2",2022
1,2022,ADAMANTINA,DRACENA,1,0,0,0,"97,72","1,74","0,54","97,75","1,86","0,39",2022
2,2022,ADAMANTINA,FLORA RICA,1,0,0,0,0,0,0,100,0,0,2022
3,2022,ADAMANTINA,FLORIDA PAULISTA,1,0,0,0,100,0,0,100,0,0,2022
4,2022,ADAMANTINA,INUBIA PAULISTA,1,0,0,0,"99,35","0,65",0,100,0,0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1969,2024,TAQUARITINGA,VISTA ALEGRE DO ALTO,1,0,0,0,100,0,0,100,0,0,2024
1970,2024,JALES,VITORIA BRASIL,1,0,0,0,100,0,0,100,0,0,2024
1971,2024,VOTORANTIM,VOTORANTIM,1,0,0,0,"99,01","0,99",0,"98,23","1,77",0,2024
1972,2024,VOTUPORANGA,VOTUPORANGA,1,0,0,0,"99,97","0,03",0,"99,75","0,25",0,2024
1973,2024,JOSE BONIFACIO,ZACARIAS,1,0,0,0,"99,28","0,72",0,"98,73","1,27",0,2024

In [20]:
# Cópia do dataframe original(Caso precise)
fluxoDFOriginal = fluxoDF.copy()
fluxoDFOriginal

,ANO_LETIVO,NM_DIRETORIA,NM_MUNICIPIO,CD_REDE_ENSINO,APR_1,REP_1,ABA_1,APR_2,REP_2,ABA_2,APR_3,REP_3,ABA_3,ANO
0,2022,ADAMANTINA,ADAMANTINA,1,0,0,0,"99,61","0,29","0,1","98,97","0,83","0,2",2022
1,2022,ADAMANTINA,DRACENA,1,0,0,0,"97,72","1,74","0,54","97,75","1,86","0,39",2022
2,2022,ADAMANTINA,FLORA RICA,1,0,0,0,0,0,0,100,0,0,2022
3,2022,ADAMANTINA,FLORIDA PAULISTA,1,0,0,0,100,0,0,100,0,0,2022
4,2022,ADAMANTINA,INUBIA PAULISTA,1,0,0,0,"99,35","0,65",0,100,0,0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1969,2024,TAQUARITINGA,VISTA ALEGRE DO ALTO,1,0,0,0,100,0,0,100,0,0,2024
1970,2024,JALES,VITORIA BRASIL,1,0,0,0,100,0,0,100,0,0,2024
1971,2024,VOTORANTIM,VOTORANTIM,1,0,0,0,"99,01","0,99",0,"98,23","1,77",0,2024
1972,2024,VOTUPORANGA,VOTUPORANGA,1,0,0,0,"99,97","0,03",0,"99,75","0,25",0,2024
1973,2024,JOSE BONIFACIO,ZACARIAS,1,0,0,0,"99,28","0,72",0,"98,73","1,27",0,2024

Normalização do dataframe

In [21]:
count = 0
# Mantemos a coluna 'ANO' (ou 'ANO_REF') fora da lista de exclusão
apagarCol = ['ANO_LETIVO','NM_DIRETORIA','CD_REDE_ENSINO','ABA_1','ABA_2']

# Percorre as colunas para adicionar as que possuam o número 3 no final (Ensino médio)
for i in fluxoDFOriginal.columns:
  if fluxoDFOriginal.columns[count][-1] == '3':
    apagarCol.append(i)
  count += 1

# Apaga as colunas da lista apagarCol
fluxoDF = fluxoDFOriginal.drop(columns=apagarCol)

Renomeação das colunas

In [22]:
fluxoDF = fluxoDF.rename(columns={
    'NM_MUNICIPIO': 'MUNICÍPIOS',
    'APR_1': 'APROVAÇÃO ANOS INICIAIS 9 ANOS',
    'APR_2': 'APROVAÇÃO ANOS FINAIS 9 ANOS',
    'REP_1': 'REPROVAÇÃO ANOS INICIAIS 9 ANOS',
    'REP_2': 'REPROVAÇÃO ANOS FINAIS 9 ANOS'
})
fluxoDF.columns

Index(['MUNICÍPIOS', 'APROVAÇÃO ANOS INICIAIS 9 ANOS',
       'REPROVAÇÃO ANOS INICIAIS 9 ANOS', 'APROVAÇÃO ANOS FINAIS 9 ANOS',
       'REPROVAÇÃO ANOS FINAIS 9 ANOS', 'ANO'],
      dtype='object')

Padronização

In [23]:
# Função auxiliar para converter strings com vírgula para float (Padronizar)
def padronizar(df, columns):
    for col in columns:
        if col in df.columns:
            # Converte para string, remove espaços, troca vírgula por ponto e converte para float
            df[col] = pd.to_numeric(df[col].astype(str).str.replace(',', '.').str.strip(), errors='coerce')
    return df

In [25]:

# fluxoDF['APROVAÇÃO ANOS INICIAIS 9 ANOS'] = padronizar(fluxoDF['APROVAÇÃO ANOS INICIAIS 9 ANOS'])

TypeError: padronizar() missing 1 required positional argument: 'columns'

Transformação das colunas e exibição apenas das necessárias para análise

In [ ]:
# Padronização dos dados
fluxoDF = fluxoDF.replace(',', '.', regex=True)
fluxoDF['APROVAÇÃO ANOS INICIAIS 9 ANOS'] = fluxoDF['APROVAÇÃO ANOS INICIAIS 9 ANOS'].astype('float')
fluxoDF['REPROVAÇÃO ANOS INICIAIS 9 ANOS'] = fluxoDF['REPROVAÇÃO ANOS INICIAIS 9 ANOS'].astype('float')
fluxoDF['APROVAÇÃO ANOS FINAIS 9 ANOS'] = fluxoDF['APROVAÇÃO ANOS FINAIS 9 ANOS'].astype('float')
fluxoDF['REPROVAÇÃO ANOS FINAIS 9 ANOS'] = fluxoDF['REPROVAÇÃO ANOS FINAIS 9 ANOS'].astype('float')

# Filtrando pela região de Campinas
fluxoDF = fluxoDF[fluxoDF.MUNICÍPIOS.isin(regiaoCampinas)]

fluxoDF = fluxoDF.reset_index(drop=True)

colunasAgrupadas = ['MUNICÍPIOS','ANO']
colunasMedia = ['APROVAÇÃO ANOS INICIAIS 9 ANOS', 'REPROVAÇÃO ANOS INICIAIS 9 ANOS', 'APROVAÇÃO ANOS FINAIS 9 ANOS', 'REPROVAÇÃO ANOS FINAIS 9 ANOS']

fluxoDF = fluxoDF.groupby(colunasAgrupadas)[colunasMedia].mean().reset_index()
fluxoDF

Download

In [ ]:
#Download do dataset unificado e normalizado
fluxoDF.to_csv('fluxoDF.csv', index=False)

### ⚪ **DATASET AUSÊNCIAS DOS PROFESSORES**

Leitura dos datasets

In [ ]:
ausLinks = {
    f"[dbo].[BASE_AUSENCIAS_{mes:02d}{ano}].csv": 2000 + ano
    for ano in [22, 23, 24]
    for mes in range(1, 13)
}

ausDF = le_dataset(URLausencia, ausLinks)
ausDF

In [ ]:
# Cópia do dataframe original(Caso precise)
ausDFOriginal = ausDF.copy()
ausDFOriginal

Normalização do dataframe

In [ ]:
# Apaga as colunas dentro da lista apagarCol
apagarCol = ['REGIAO_EXERC', 'DE_EXERC', 'NOME_UA_EXERC', 'NOME_CARGO_EXERC', 'CIE_ESCOLA', 'UA_EXERC', 'DI', 'CARGO_EXERC', 'CATEG_E']
ausDF = ausDFOriginal.drop(columns=apagarCol)

# Normaliza todos os municípios dentro da coluna para que não haja espaços vazios e todos sejam maiúsculos
ausDF['MUNICIPIO_EXERC'] = ausDF['MUNICIPIO_EXERC'].str.strip().str.upper()

# Seleciona apenas os municípios da região de Campinas
ausDF = ausDF[ausDF['MUNICIPIO_EXERC'].isin(regiaoCampinas)]

ausDF = ausDF.rename(columns={
    'MUNICIPIO_EXERC': 'MUNICÍPIOS',
    'TT_DIAS_FALTA_JUST': 'TOTAL FALTAS JUST',
    'TT_DIAS_FALTA_INJUST': 'TOTAL FALTAS INJUST',
})

ausDF['TOTAL DIAS AUSENTES'] = (ausDF['TOTAL FALTAS JUST'] + ausDF['TOTAL FALTAS INJUST'])

ausDF = (ausDF.groupby(['MUNICÍPIOS','ANO'])[['TOTAL FALTAS JUST','TOTAL FALTAS INJUST', 'TOTAL DIAS AUSENTES']].sum().reset_index())

ausDF

Download

In [ ]:
ausDF.to_csv('ausDF.csv', index=False)

### ⚪ **DATASET CENSO ESCOLAR**

In [ ]:
links_censo = {
    2022: "censo_escolar_2022_sp_estadual.csv",
    2023: "censo_escolar_2023_sp_estadual.csv",
    2024: "censo_escolar_2024_sp_estadual.csv",
}

censoDF = le_dataset(URLcenso, links_censo)
censoDF

In [ ]:
# Cópia do dataframe original(Caso precise)
censoDFOriginal = censoDF.copy()
censoDFOriginal

In [ ]:
censoDF['NO_MUNICIPIO'] = censoDFOriginal['NO_MUNICIPIO'].str.strip().str.upper()
censoDF = censoDF[censoDF['NO_MUNICIPIO'].isin(municipios_rmc)].reset_index(drop=True)

def normalizar(texto):
    return unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('ascii').upper().strip()

censoDF['NO_MUNICIPIO'] = censoDF['NO_MUNICIPIO'].apply(normalizar)
censoDF = censoDF[censoDF['NO_MUNICIPIO'].isin(regiaoCampinas].reset_index(drop=True)

censoDF = censoDF.rename(columns={'NO_MUNICIPIO': 'MUNICÍPIOS'})

# Agrega por município e ano (soma matrículas e docentes, média de infraestrutura)
censoDF = censoDF.groupby(['MUNICÍPIOS', 'ANO']).agg(
    TOTAL_DOCENTES            = ('QT_DOC_BAS', 'sum'),
    TOTAL_MATRICULAS          = ('QT_MAT_BAS', 'sum'),
    MATRICULAS_ANOS_INICIAIS  = ('QT_MAT_FUND_AI', 'sum'),
    MATRICULAS_ANOS_FINAIS    = ('QT_MAT_FUND_AF', 'sum'),
    ESCOLAS_COM_BIBLIOTECA    = ('IN_BIBLIOTECA', 'sum'),
    ESCOLAS_COM_LAB_INFO      = ('IN_LABORATORIO_INFORMATICA', 'sum'),
    ESCOLAS_COM_INTERNET      = ('IN_INTERNET', 'sum'),
    ESCOLAS_COM_QUADRA        = ('IN_QUADRA_ESPORTES', 'sum'),
    ESCOLAS_COM_REFEITORIO    = ('IN_REFEITORIO', 'sum'),
).reset_index().round(2)

censoDF

---
## **📊 | ANÁLISE EXPLORATÓRIA**

In [ ]:
# Cálculo dos limites para tratar os outliers
Q1 = sarespDF['MÉDIA_PROFICIÊNCIA'].quantile(0.25)

Q3 = sarespDF['MÉDIA_PROFICIÊNCIA'].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# -----------------------------------

print(sarespDF['MÉDIA_PROFICIÊNCIA'].describe())
plt.figure(figsize=(10, 6))
sns.boxplot(data=sarespDF, x=sarespDF.MUNICÍPIOS, y=sarespDF.MÉDIA_PROFICIÊNCIA, hue=sarespDF["MUNICÍPIOS"])
plt.title("Média de proficiência por município")
plt.xticks(fontsize=8, rotation=30)
plt.xlabel("Municípios")
plt.ylabel("Média de Proficiência")
plt.ylim(limite_inferior,limite_superior)
plt.show()

## **📊 | GRAFOS**